{
 "title": "Lean Ethereum Clients Dashboard",
 "tags": [
  "interop",
  "Client"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "label_values(network)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(lean_node_info{network=~\"$network\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(lean_node_info{network=~\"$network\", job=~\"$job\"}, instance)"
    }
   },
   { "name": "datasourse", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(network) (lean_node_start_time_seconds{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"} * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by(network) (lean_validators_count{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of attestation committees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max by(network) (lean_attestation_committee_count{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators list",
   "type": "piechart",
   "description": "Number of validators attached to each node",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (lean_validators_count)", "legendFormat": "Total" },
    {
     "expr": "sum by (network, job, instance) (lean_validators_count{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Aggregators",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max by(network,job,instance) (lean_is_aggregator{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}) > 0",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(lean_node_info{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest finalized slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by(network) (lean_latest_finalized_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "max by(network) (lean_latest_justified_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "max by(network) (lean_head_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Latest finalized slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (network, job, instance)(lean_latest_finalized_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": " sum by (network, job, instance) (lean_latest_justified_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": " sum by (network, job, instance) (lean_head_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Current slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": " sum by (network, job, instance) (lean_current_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "changes(lean_node_start_time_seconds{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Attestation committee subnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (network, job, instance) (lean_attestation_committee_subnet{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connected peers per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": " sum by (network, job, instance) (lean_connected_peers{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node sync status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "max by (network, job, instance) (\n  (lean_node_sync_status{status=\"synced\", network=~\"$network\", job=~\"$job\", instance=~\"$instance\"} == 1) * 2\n  or\n  (lean_node_sync_status{status=\"syncing\", network=~\"$network\", job=~\"$job\", instance=~\"$instance\"} == 1) * 1\n  or\n  (lean_node_sync_status{status=\"idle\", network=~\"$network\", job=~\"$job\", instance=~\"$instance\"} == 1) * 0\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations - Success",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (increase(lean_finalizations_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\", result=\"success\"}[1m]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (increase(lean_finalizations_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\", result=\"error\"}[1m]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalization/Justification Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Head - Finalized  delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "avg_over_time(lean_head_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m]) - avg_over_time(lean_latest_finalized_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head - Justified delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "avg_over_time(lean_head_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m]) - avg_over_time(lean_latest_justified_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Justified - Finalized  delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "expr": "avg_over_time(lean_latest_justified_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m]) - avg_over_time(lean_latest_finalized_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Connected peers per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": " sum by (network, job, instance) (lean_connected_peers{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connected peers per node (detailed)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": " sum by (job, client) (lean_connected_peers{job=~\"$job\", client!=\"\"})",
     "legendFormat": "{{job}} - {{client}}"
    }
   ]
  },
  {
   "title": "Peer connection events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (network, job, instance) (\n    increase(lean_peer_connection_events_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Peer disconnection events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum by (network, job, instance) (\n    increase(lean_peer_disconnection_events_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  { "title": "Gossip messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Bytes size of a gossip block message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_gossip_block_size_bytes_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Bytes size of a gossip attestation message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_gossip_attestation_size_bytes_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Bytes size of a gossip aggregated attestation message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_gossip_aggregation_size_bytes_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "PQ Signatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Total number of attestation signatures",
   "type": "timeseries",
   "description": "Total number of individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n    increase(lean_pq_sig_attestation_signatures_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of valid attestation signatures",
   "type": "timeseries",
   "description": "Total number of valid individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n    increase(lean_pq_sig_attestation_signatures_valid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of invalid attestation signatures",
   "type": "timeseries",
   "description": "Total number of invalid individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n    increase(lean_pq_sig_attestation_signatures_invalid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to sign an attestation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_pq_sig_attestation_signing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify an attestation signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_pq_sig_attestation_verification_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n    increase(lean_pq_sig_aggregated_signatures_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of attestations included into aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n    increase(lean_pq_sig_attestations_in_aggregated_signatures_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of valid aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n    increase(lean_pq_sig_aggregated_signatures_valid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of invalid aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n    increase(lean_pq_sig_aggregated_signatures_invalid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to build an aggregated signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_pq_sig_attestation_signatures_building_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify an aggregated signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_pq_sig_aggregated_signatures_verification_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Block production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Number of aggregated payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_block_aggregated_payloads_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to build aggregated payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_block_building_payload_aggregation_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful block builds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": " avg_over_time (\n  sum by (network, job, instance) (\n    (lean_block_building_success_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})\n  )[2m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Failed block builds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "targets": [
    {
     "expr": " avg_over_time (\n  sum by (network, job, instance) (\n    (lean_block_building_failures_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})\n  )[2m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to build a block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_block_building_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Fork-Choice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in fork-choice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_fork_choice_block_processing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to aggregate committee signatures",
   "type": "timeseries",
   "description": "Time taken to process block in fork-choice",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_committee_signatures_aggregation_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of fork choice reorgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "sum by (network, job, instance) (\n  increase(lean_fork_choice_reorgs_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Depth of fork choice reorgs (in blocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_fork_choice_reorg_depth_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Number of gossip signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": " avg_over_time (\n  sum by (network, job, instance) (\n    (lean_gossip_signatures{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})\n  )[2m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of new aggregated payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 161 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n   (lean_latest_new_aggregated_payloads{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})\n  )[2m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of known aggregated payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 161 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n   (lean_latest_known_aggregated_payloads{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})\n  )[1m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "FC Valid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 170 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (\n    increase(lean_attestations_valid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "FC Invalid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 170 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (increase(lean_attestations_invalid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "FC Attestations validation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_attestation_validation_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Safe target slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 178 },
   "targets": [
    {
     "expr": " sum by (network, job, instance) (lean_safe_target_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Processed attestations",
   "type": "timeseries",
   "description": "Total number of attestations processed in state transition function",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 178 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (increase(lean_state_transition_attestations_processed_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Attestations processing time",
   "type": "timeseries",
   "description": "Time taken to process attestations in state transition function",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_attestations_processing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to produce attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_attestations_production_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Time taken to aggregate committee signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_committee_signatures_aggregation_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "State Transition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 } },
  {
   "title": "State transition time",
   "type": "timeseries",
   "description": "Time taken to process state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_block_processing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processed slots",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 203 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (increase(lean_state_transition_slots_processed_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Slots processing time",
   "type": "timeseries",
   "description": "Time taken to process slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_slots_processing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations - Success",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 211 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (increase(lean_finalizations_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\", result=\"success\"}[1m]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 211 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (network, job, instance) (increase(lean_finalizations_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\", result=\"error\"}[1m]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}